# =============================================================================
# Railway Configuration for COVID-19 KMS Backend
# =============================================================================

[build]
builder = "nixpacks"

[deploy]
startCommand = "./main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
HOST = "0.0.0.0"
PORT = "8000"
ENV = "production"
LOG_LEVEL = "INFO"
DEBUG = "false"
LOG_FORMAT = "json"

# Database will be set by Railway PostgreSQL service
# DATABASE_URL will be automatically injected by Railway

# ETL Configuration
ETL_BATCH_SIZE = "100"
ETL_TIMEOUT_SECONDS = "300"
ETL_MAX_RETRIES = "3"

# Security
CORS_ALLOWED_ORIGINS = "*"
API_KEY_HEADER = "X-API-Key"
RATE_LIMIT_PER_MINUTE = "60"

# External Services
YOUTUBE_API_QUOTA_LIMIT = "10000"
NEWS_API_QUOTA_LIMIT = "1000"

